
name: CI pipeline maven based java application

env:
  REGISTRY: docker.io/ranjith413
  APP_NAME: order-service

on:
  push:
    branches:
      - main
    paths:
      - 'apps/order-service/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and verify with maven
      run: |
        cd apps/order-service/
        mvn clean verify
    
    #- name: Static code Analysis
    #  run: mvn sonar:sonar \
    #    -Dsonar.projectkey=<project_key> \
    #    -Dsonar.host.url=$SONAR_HOST_URL
    #    -Dsonar.login={{ secrets.SONAR_TOKEN }}

    - name: Create Image tag
      run: |
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "IMAGE_TAG=${{ github.ref_name }}-$SHORT_SHA-${{ github.run_number }}" >> $GITHUB_ENV
        
    
    - name: Image build
      run: |
        cd apps/order-service/
        docker build -t $REGISTRY/$APP_NAME:$IMAGE_TAG .

    - name: Image push
      run: |
        echo "${{secrets.DOCKER_PASSWD}}" | \
        docker login -u ranjith413 --password-stdin
        docker push $REGISTRY/$APP_NAME:$IMAGE_TAG
        docker logout

